/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type AchievementCategory = 'combat' | 'hidden' | 'progression' | 'social' | 'special'

export type GameMode =
  | 'elimination'
  | 'free_for_all'
  | 'mutation'
  | 'search_destroy'
  | 'team_deathmatch'
  | 'zombie'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type LeaderboardPeriod = 'all_time' | 'daily' | 'monthly' | 'weekly'

export type Numeric = ColumnType<string, number | string, number | string>

export type RoomStatus = 'cancelled' | 'completed' | 'in_progress' | 'starting' | 'waiting'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export type WeaponRarity = 'common' | 'epic' | 'legendary' | 'rare' | 'uncommon'

export type WeaponType =
  | 'assault_rifle'
  | 'grenade'
  | 'machine_gun'
  | 'melee'
  | 'pistol'
  | 'shotgun'
  | 'smg'
  | 'sniper'

export interface AchievementCriteria {
  achievement_id: string
  condition_key: string
  created_at: Generated<Timestamp>
  game_mode: GameMode | null
  id: Generated<string>
  operator: Generated<string | null>
  target_value: number
  weapon_type: WeaponType | null
}

export interface Achievements {
  achievement_key: string
  category: AchievementCategory
  created_at: Generated<Timestamp>
  description: string | null
  icon_url: string | null
  id: Generated<string>
  is_hidden: Generated<boolean | null>
  name: string
  sort_order: Generated<number | null>
  xp_reward: Generated<number>
}

export interface Friendships {
  addressee_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  requester_id: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface GameRooms {
  completed_at: Timestamp | null
  config_id: string
  created_at: Generated<Timestamp>
  current_players: Generated<number | null>
  host_player_id: string
  id: Generated<string>
  map_id: string
  name: string | null
  password_hash: string | null
  room_code: string | null
  started_at: Timestamp | null
  status: Generated<RoomStatus>
}

export interface LeaderboardEntries {
  id: Generated<string>
  last_updated: Generated<Timestamp>
  leaderboard_id: string
  matches_count: Generated<number>
  metric_value: Int8
  period_end: Timestamp
  period_start: Timestamp
  player_id: string
  rank: number
}

export interface Leaderboards {
  created_at: Generated<Timestamp>
  game_mode: GameMode | null
  id: Generated<string>
  is_active: Generated<boolean>
  metric_key: string
  min_matches_required: Generated<number | null>
  name: string
  period_type: LeaderboardPeriod
}

export interface Levels {
  created_at: Generated<Timestamp>
  level: number
  rewards: Generated<Json | null>
  title: string
  xp_required: Int8
}

export interface Maps {
  created_at: Generated<Timestamp>
  description: string | null
  id: Generated<string>
  is_active: Generated<boolean | null>
  map_key: string
  max_players: number
  name: string
  size_category: string | null
  supported_modes: string[]
  thumbnail_url: string | null
}

export interface Matches {
  completed_at: Generated<Timestamp>
  duration_seconds: number
  game_mode: GameMode
  id: Generated<string>
  map_id: string
  mvp_player_id: string | null
  room_id: string | null
  started_at: Timestamp
  winning_team: number | null
}

export interface MatchEvents {
  damage_amount: number | null
  event_type: string
  hit_zone: string | null
  match_id: string
  metadata: Generated<Json | null>
  position_x: number | null
  position_y: number | null
  position_z: number | null
  round_number: number | null
  source_player_id: string | null
  target_player_id: string | null
  tick_number: number | null
  time: Timestamp
  weapon_id: string | null
}

export interface MatchParticipants {
  assists: Generated<number>
  created_at: Generated<Timestamp>
  damage_dealt: Generated<Int8>
  damage_received: Generated<Int8>
  deaths: Generated<number>
  detailed_stats: Generated<Json | null>
  headshots: Generated<number>
  id: Generated<string>
  is_winner: Generated<boolean>
  kills: Generated<number>
  match_id: string
  player_id: string
  playtime_seconds: Generated<number>
  position: number | null
  score: Generated<number>
  team: number | null
  xp_gained: Generated<number>
}

export interface MatchWeaponUsage {
  damage_dealt: Generated<Int8 | null>
  headshots: Generated<number | null>
  id: Generated<string>
  kills: Generated<number | null>
  match_participant_id: string
  shots_fired: Generated<number | null>
  shots_hit: Generated<number | null>
  weapon_id: string
}

export interface PlayerAchievements {
  achievement_id: string
  player_id: string
  progress: Generated<Json | null>
  unlocked_at: Generated<Timestamp>
}

export interface PlayerInventory {
  acquired_at: Generated<Timestamp>
  expires_at: Timestamp | null
  id: Generated<string>
  is_permanent: Generated<boolean | null>
  player_id: string
  weapon_id: string
}

export interface PlayerLoadouts {
  created_at: Generated<Timestamp>
  flash_grenades: Generated<number | null>
  frag_grenades: Generated<number | null>
  id: Generated<string>
  is_default: Generated<boolean | null>
  melee_weapon_id: string | null
  name: Generated<string>
  player_id: string
  primary_attachments: Generated<string[] | null>
  primary_weapon_id: string | null
  secondary_attachments: Generated<string[] | null>
  secondary_weapon_id: string | null
  slot: Generated<number>
  smoke_grenades: Generated<number | null>
  updated_at: Generated<Timestamp>
}

export interface PlayerProgression {
  current_level: Generated<number>
  current_xp: Generated<Int8>
  last_updated: Generated<Timestamp>
  player_id: string
  total_xp: Generated<Int8>
  xp_booster_expires: Timestamp | null
  xp_multiplier: Generated<Numeric | null>
}

export interface Players {
  avatar_url: string | null
  bio: string | null
  created_at: Generated<Timestamp>
  display_name: string
  id: Generated<string>
  language: Generated<string | null>
  region: Generated<string | null>
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface PlayerStats {
  last_updated: Generated<Timestamp>
  matches_lost: Generated<number>
  matches_won: Generated<number>
  mode_stats: Generated<Json | null>
  player_id: string
  playtime_seconds: Generated<Int8>
  total_assists: Generated<Int8>
  total_damage_dealt: Generated<Int8>
  total_damage_received: Generated<Int8>
  total_deaths: Generated<Int8>
  total_headshots: Generated<Int8>
  total_kills: Generated<Int8>
  total_matches: Generated<number>
  total_score: Generated<Int8>
}

export interface PlayerTelemetry {
  assists: Generated<number | null>
  damage_dealt: Generated<Int8 | null>
  damage_received: Generated<Int8 | null>
  deaths: Generated<number | null>
  fps_avg: number | null
  kills: Generated<number | null>
  match_id: string
  packet_loss_pct: Numeric | null
  ping_ms: number | null
  player_id: string
  score: Generated<number | null>
  time: Timestamp
}

export interface RoomConfigs {
  created_at: Generated<Timestamp>
  game_mode: GameMode
  id: Generated<string>
  is_official: Generated<boolean | null>
  is_ranked: Generated<boolean | null>
  max_players: Generated<number>
  min_players: Generated<number>
  name: string
  round_limit: number | null
  score_limit: number | null
  time_limit_seconds: number | null
}

export interface RoomParticipants {
  id: Generated<string>
  is_ready: Generated<boolean | null>
  joined_at: Generated<Timestamp>
  left_at: Timestamp | null
  loadout_id: string | null
  player_id: string
  room_id: string
  team: number | null
}

export interface SchemaMigrations {
  dirty: boolean
  version: Int8
}

export interface ServerMetrics {
  active_players: number | null
  active_rooms: number | null
  bytes_in: Int8 | null
  bytes_out: Int8 | null
  connections: number | null
  cpu_percent: Numeric | null
  memory_mb: Int8 | null
  server_id: string
  tick_rate_avg: Numeric | null
  time: Timestamp
}

export interface Sessions {
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  ip_address: string | null
  refresh_token: string
  revoked_at: Timestamp | null
  user_agent: string | null
  user_id: string
}

export interface Users {
  ban_reason: string | null
  banned_until: Timestamp | null
  created_at: Generated<Timestamp>
  email: string
  email_verified: Generated<boolean | null>
  id: Generated<string>
  is_active: Generated<boolean>
  is_banned: Generated<boolean>
  last_login_at: Timestamp | null
  password_hash: string
  updated_at: Generated<Timestamp>
  username: string
}

export interface WeaponAttachments {
  attachment_type: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  is_active: Generated<boolean | null>
  name: string
  stat_modifiers: Generated<Json>
  unlock_level: Generated<number | null>
  weapon_id: string | null
}

export interface Weapons {
  accuracy: Numeric | null
  base_damage: number
  created_at: Generated<Timestamp>
  description: string | null
  fire_rate: Numeric | null
  id: Generated<string>
  is_active: Generated<boolean>
  magazine_size: number | null
  move_speed_modifier: Generated<Numeric | null>
  name: string
  range_meters: number | null
  rarity: Generated<WeaponRarity>
  reload_time: Numeric | null
  stats: Generated<Json | null>
  unlock_cost: Generated<number | null>
  unlock_level: Generated<number | null>
  weapon_key: string
  weapon_type: WeaponType
}

export interface XpHistory {
  base_amount: number
  final_amount: number
  gained_at: Generated<Timestamp>
  id: Generated<string>
  match_id: string | null
  multiplier: Generated<Numeric | null>
  player_id: string
  source: string
}

export interface DB {
  achievement_criteria: AchievementCriteria
  achievements: Achievements
  friendships: Friendships
  game_rooms: GameRooms
  leaderboard_entries: LeaderboardEntries
  leaderboards: Leaderboards
  levels: Levels
  maps: Maps
  match_events: MatchEvents
  match_participants: MatchParticipants
  match_weapon_usage: MatchWeaponUsage
  matches: Matches
  player_achievements: PlayerAchievements
  player_inventory: PlayerInventory
  player_loadouts: PlayerLoadouts
  player_progression: PlayerProgression
  player_stats: PlayerStats
  player_telemetry: PlayerTelemetry
  players: Players
  room_configs: RoomConfigs
  room_participants: RoomParticipants
  schema_migrations: SchemaMigrations
  server_metrics: ServerMetrics
  sessions: Sessions
  users: Users
  weapon_attachments: WeaponAttachments
  weapons: Weapons
  xp_history: XpHistory
}

export type Database = DB
